### ISSUE TITLE
Having error while generating client certificate from Downloaded CSR.

### ISSUE THREAD

**Issue by singhpavittar** [saltedge/saltedge-examples#61]
Hi,
I'm trying to generate the certificate from the download CSR. I'm following the https://docs.saltedge.com/account_information/v5/#before_going_live and in the second point i have to generate certificate use the signature to call the API. I'm using this command to generate certificate 

> openssl x509 -req -days 365 -in salt_edge_callbacks.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out client.crt

this is the output i'm getting.

> Signature ok
subject=/C=/ST=/L=/O=/CN=
Error opening CA Certificate ca.crt
140735626965960:error:02001002:system library:fopen:No such file or directory:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.50.3/libressl/crypto/bio/bss_file.c:255:fopen('ca.crt', 'r')
140735626965960:error:20074002:BIO routines:FILE_CTRL:system lib:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.50.3/libressl/crypto/bio/bss_file.c:257:
unable to load certificate

Can you please help in this. I'm using mac.

Thanks in advance.

**Comment by vlad1803** [comment]
Hi,
There was a wrong link for instructions, now it is fixed to this one: https://docs.saltedge.com/general/#signature. Hope this will help. If you will need help, please let us know.

Sorry for the inconvenience.

**Comment by singhpavittar** [comment]
Hi, @vlad1803 can you help me in this. I have connect to bank via opening https://docs.saltedge.com/account_information/v5/#visit-connect-url 
and after this page redirected to another url. 
but how can i get the connection after connecting bank, the docs are confusing.
Thanks in advance

**Comment by vlad1803** [comment]
Hi @singhpavittar, 
You can do one of the following steps:
- when you redirected to success url, fetch all connections for your customer using https://docs.saltedge.com/account_information/v5/#connections-list, then choose connection you need and go further with https://docs.saltedge.com/account_information/v5/#fetch-accounts-for-connections.
- If for now you can't trigger fetching connections when you are redirected to success url, then you can try https://docs.saltedge.com/account_information/v5/#embedding-connect-in-your-application which will allow you to receive javascript callbacks. When you receive https://docs.saltedge.com/account_information/v5/#success callback, you can use `connection_id` from response to obtain connection that you needed using https://docs.saltedge.com/account_information/v5/#connections-show.

**Comment by singhpavittar** [comment]
@vlad1803 after success url, when i'm fetching connections https://docs.saltedge.com/account_information/v5/#connections-list
i'm getting this error.

> {"error":{"class":"CustomerNotFound","message":"Customer with secret: '' was not found.","documentation_url":"https://docs.saltedge.com/account_information/v5/#errors-customer_not_found"},"request":{"customer_id":"4498396"}}

if i send the customer secret in the API then i will get this error.

> {"error":{"class":"AppsRestricted","message":"Not available for apps.","documentation_url":"https://docs.saltedge.com/account_information/v5/#errors-apps_restricted"},"request":{"customer_id":"4498396"}}

**Comment by vlad1803** [comment]
@singhpavittar. This is because on this step https://docs.saltedge.com/account_information/v5/#create-api-keys you created `API keys` for `apps`, but in quick start guide `API keys` is created for `service`.

-  https://docs.saltedge.com/account_information/v5/#connections-list is for `service` type only.

Here is couple of solutions:

1. if you are creating an integration that is intended to be used by backends, you can create `API keys` for `service` and https://docs.saltedge.com/account_information/v5/#connections-list will be available for you.

2. you can use javascript callbacks to obtain `connection_secret` which you can use to get connection: https://docs.saltedge.com/account_information/v5/#connections-show

The following link will help you to choose authentication what is suitable for you: https://docs.saltedge.com/general/#services_and_apps_authentication
